### ISSUE TITLE
Implementing scoring function for GMPE with no or more than one non-linear coefficient 

### ISSUE THREAD

**Issue by zbadmus** [mingdeyu/GMPE-estimation#1]
Good day Sir. Please find listed below of the issues I have using the scoring function:

1. Updates of estimates are complex numbers due to the update of second element in gamma being negative.

2. Unable to obtain asymptotic standard error of the estimates

3. outputs are 'NaN' when trying a GMPE with no non-linear coefficient 

Thank you.

**Comment by mingdeyu** [comment]
@zbadmus thanks for letting me know. The function now has been updated to address the issues you reported. The descriptions in the function file and the Readme file are also updated accordingly. Please have a try and let me know if there are still issues. Many thanks!
